### ISSUE TITLE
snippets doesn't follow editor's indent rule

### ISSUE THREAD

**Issue by carlosliu** [zenorocha/atom-javascript-snippets#15]
I normally set tab and indent size to 4. The snippets in this package always force 2 space indentation. I have noticed that snippets in the language-javascript package use \t instead of space. That works pretty well, and editor can replace leading tab to preferred indent size automatically.

**Comment by martinleopold** [comment]
just what I wanted to suggest, right now.
btw @zenorocha, thanks for this great snippet collection, fits me pretty well.

**Comment by zenorocha** [comment]
Fixed in https://github.com/zenorocha/atom-javascript-snippets/pull/16

**Comment by zenorocha** [comment]
Thanks @martinleopold!
