### ISSUE TITLE
Wrong tab size

### ISSUE THREAD

**Issue by irobert91** [zenorocha/atom-javascript-snippets#23]
Hello

I have noticed that all snippets are hardcoded to soft tabs of size 2.
That is not very convenient if the rest of your code uses tabs of any other size.
Is there a specific reason for this? Am I the only one bothered by it?

By the way, I would gladly submit a pull request to fix it.

**Comment by johngrogg** [comment]
Agreed, rather annoying if you work with any other size of soft tabs.

**Comment by zenorocha** [comment]
I agree that's really annoying but there's not much I can do. If I change to spaces other people will complain about it :/

**Comment by irobert91** [comment]
Shouldn't atom replace `\t` with whatever tab size and style the user set?

**Comment by zenorocha** [comment]
That's what I expect too
