### ISSUE TITLE
Support alternative JS sources?

### ISSUE THREAD

**Issue by lukehorvat** [zenorocha/atom-javascript-snippets#24]
JavaScript sources may not always have a `.js` file extension. Any plans to support others?

Atom lets you specify multiple comma-separated sources like so:

```cson
".source.js, .source.jsx":
  "forEach":
    "prefix": "fe"
    "body": """
    ${1:myArray}.forEach(function(${2:elem}) {
    \t${0:// body...}
    });
    """
```

**Comment by zenorocha** [comment]
Sounds good, could you open a PR?

**Comment by lukehorvat** [comment]
Sure. You happy for me to add .jsx to every snippet, or just a subset?

**Comment by hourliert** [comment]
Hi,
Maybe you could support typescript too? That would be amazing!

**Comment by zenorocha** [comment]
Done for JSX and TypeScript! lol

Thanks @lukehorvat and @hourliert for suggesting ;)
