### ISSUE TITLE
createDocumentFragment() does not take argument

### ISSUE THREAD

**Issue by nykh** [zenorocha/atom-javascript-snippets#35]
Hi, there is a mistake in the snippets. The createDocumentFragment() does not take an argument.

https://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-35CB04B5

Can you push a fast fix? Or I will do a tentative manual fix.

**Comment by zenorocha** [comment]
Fixed on https://github.com/zenorocha/atom-javascript-snippets/commit/5ecec317e2cc38024e9776dfb6c8308f1924613d!

Thanks for reporting @nykh ;)
