### ISSUE TITLE
Add option to remove semicolon

### ISSUE THREAD

**Issue by lbineau** [zenorocha/atom-javascript-snippets#48]
I use your snippets really often but I'm working with [Standard](http://standardjs.com/rules.html) rules so it doesn't allow semicolons. So I have to remove them each time.
Would it be possible to remove it with an option ?

**Comment by tanpengsccd** [comment]
Me too! 
Hope to add a option to omit semicolon ! it will be more perfect!

**Comment by zenorocha** [comment]
Hey @lbineau,

First of all, sorry for taking so long to reply. I like this idea but I'm not sure if it's easy to execute it. We would need another repository with the same snippets but without semicolon :/

I'm open for pull requests if there's a way to add an option to this.
