### ISSUE TITLE
Redundant complement

### ISSUE THREAD

**Issue by rafa-acioly** [zenorocha/atom-javascript-snippets#51]
In the shortcut "ae" the code is produced:

```
$ {1: document} .addEventListener ('$ {2: event}', function () {
  $ {0: // body ...}
});
```
But people do not always use functions written directly in the "addEventListener" as in the example below;

element.addEventListener('xpto', myfunction);

What I suggest is to remove the anonymous function from within the "ae" shortcut and if the user wishes to add an anonymous function use the "afn" shortcut.
My shortcut is like this;

```$ {1: document} .addEventListener ('$ {2: event}', $ {0:});```

So when I need to use the shortcut just type:

"ae" + tab;
type the name of the element + tab;
type the desired event + tab;
type "afn" + tab.

If I do not want to use an anonymous function, I just type the name of my external function.

**Comment by zenorocha** [comment]
Hey @rafa-acioly.

First of all, sorry for taking so long to reply. I understand your idea but I think the most common use case is people writing anonymous function.

Thanks for your feedback!
